// Code generated by MockGen. DO NOT EDIT.
// Source: service/profile.service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	dto "monorepo/internal/dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProfileServiceInterface is a mock of ProfileServiceInterface interface.
type MockProfileServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProfileServiceInterfaceMockRecorder
}

// MockProfileServiceInterfaceMockRecorder is the mock recorder for MockProfileServiceInterface.
type MockProfileServiceInterfaceMockRecorder struct {
	mock *MockProfileServiceInterface
}

// NewMockProfileServiceInterface creates a new mock instance.
func NewMockProfileServiceInterface(ctrl *gomock.Controller) *MockProfileServiceInterface {
	mock := &MockProfileServiceInterface{ctrl: ctrl}
	mock.recorder = &MockProfileServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileServiceInterface) EXPECT() *MockProfileServiceInterfaceMockRecorder {
	return m.recorder
}

// GetProfile mocks base method.
func (m *MockProfileServiceInterface) GetProfile(ctx context.Context) (*dto.ResponseGetProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx)
	ret0, _ := ret[0].(*dto.ResponseGetProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockProfileServiceInterfaceMockRecorder) GetProfile(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockProfileServiceInterface)(nil).GetProfile), ctx)
}

// UpdateProfile mocks base method.
func (m *MockProfileServiceInterface) UpdateProfile(ctx context.Context, userID string, data dto.RequestUpdateProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileServiceInterfaceMockRecorder) UpdateProfile(ctx, userID, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileServiceInterface)(nil).UpdateProfile), ctx, userID, data)
}
