name: Build Svc User Main

on:
  push:
    branches: [main]
    paths: [services/user/**]

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    # continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    # Run TruffleHog inside Docker container
    - name: Secret Scanning with TruffleHog
      continue-on-error: true
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/workspace \
        -w /workspace \
        trufflesecurity/trufflehog:latest filesystem . \
        --exclude-paths trufflehog-excluded-paths.txt \
        --fail --json --no-update > ${{ github.workspace }}/trufflehog-scan-result.json
     
    # Archive the TruffleHog JSON result as an artifact
    - name: Archive TruffleHog Scan Result
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: trufflehog-scan-result
        path: ${{ github.workspace }}/trufflehog-scan-result.json
        
  build:
    runs-on: ubuntu-latest
    needs: [secret-scanning]
    environment: akasia-acr
    steps:
    # Checkout Branch
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run Unit Tests
      run: go test ./services/user/... >> test-output.log

    - name: Run Coverage Tests
      run: go test -cover ./services/user/... >> test-output.log

    - name: Archive Test Logs
      uses: actions/upload-artifact@v3
      with:
        name: go-test-logs
        path: test-output.log

    # Setting up Docker Builder
    - name: Set up Docker Builder
      uses: docker/setup-buildx-action@v3

    #login alibaba Container Registry
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: "${{ secrets.REGISTRY_ADDR }}"
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"
    - name: Build and push image
      env:
        IMAGE_TAG: main
        FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
      shell: bash
      run: |
        echo "$FIREBASE_JSON" >> ./services/user/config/service-account.json
        cat ./services/user/config/service-account.json
        docker build -f Dockerfile-user --build-arg DIR=user -t registry-intl.ap-southeast-5.aliyuncs.com/akasia/akasia-be:$IMAGE_TAG .
        docker push registry-intl.ap-southeast-5.aliyuncs.com/akasia/akasia-be:$IMAGE_TAG
        