name: Build Svc Clinic 

on:
  push:
    branches: [main]
    paths: [services/clinic/**]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: akasia-acr
    steps:
    # Checkout Branch
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run Unit Tests
      run: go test ./services/clinic/... >> test-output.log

    - name: Run Coverage Tests
      run: go test -cover ./services/clinic/... >> test-output.log

    - name: Archive Test Logs
      uses: actions/upload-artifact@v3
      with:
        name: go-test-logs
        path: test-output.log

    # Setting up Docker Builder
    - name: Set up Docker Builder
      uses: docker/setup-buildx-action@v3

    #login alibaba Container Registry
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: "${{ secrets.REGISTRY_ADDR }}"
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"

    - name: Build and push image
      env:
        IMAGE_TAG: main
        IMAGE: ${{ vars.IMAGE }}
      shell: bash
      run: |
        docker build  -f --build-arg DIR=clinic -t $IMAGE:$IMAGE_TAG .
        docker push $IMAGE:$IMAGE_TAG
        