name: Build & Push Svc medical-record 

on:
  push:
    branches: [main,do/cicd-weigh-goal]
    paths: [services/medical-record/**]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: akasia-acr
    steps:
    # Checkout Branch
    - uses: actions/checkout@v3

    # Setting up Docker Builder
    - name: Set up Docker Builder
      uses: docker/setup-buildx-action@v3

    #login alibaba Container Registry
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: "${{ secrets.REGISTRY_ADDR }}"
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"

    - name: Build and push image
      env:
        IMAGE_TAG: main
        REPO_IMAGE: registry-intl.ap-southeast-5.aliyuncs.com/akasia/medical-record
      shell: bash
      run: |
        docker build --build-arg DIR=medical-record -t $REPO_IMAGE:$IMAGE_TAG .
        docker push $REPO_IMAGE:$IMAGE_TAG
        